hive> create database starwars;
hive> use starwars;
hive> select COUNT(*) from episode4 where INSTR(dialogues, 'Luke')>0;
hive> INSERT OVERWRITE LOCAL DIRECTORY '/totalLuke'  select COUNT(*) from episode4 where INSTR(dialogues, 'Luke')>0;
hive> INSERT OVERWRITE DIRECTORY 'user/maha/totalLuke' ROW FORMAT DELIMITED FIELDS TERMINATED BY '\t' select COUNT(*) from episode4 where INSTR(dialogues, 'Luke')>0;